name: Build scl
runs:
  using: "composite"
  steps:
  - name: Install trial run 
    run: git clone https://github.com/unlink2/trialrun 
    shell: bash
  - name: Build trialrun
    run: cd trialrun && make && sudo make install
    shell: bash
