
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/scl
    - uses: ./.github/actions/tr
    - name: Install dependencies
      run: sudo apt install libcmocka-dev bear
    - name: Run lint 
      run: echo "Lint disabled" # make buildcmd && make lint
    - name: Run tests
      run: make test
    - name: Run trialrun 
      run: make int
